### Post stuff

POST http://localhost:3000/stuff/add
Content-Type: application/json

{
  "content": {
    "name": "Robot",
    "description": "There is a loose killer Robot out there",
    "category": "terminator"
  }
}