### Post stuff

POST http://localhost:3000/stuff/add
Content-Type: application/json

{
  "content": {
    "name": "Big Mountain",
    "description": "Somewhere in another world",
    "category": "exoplanets"
  }
}